name: Github CI/CD pipeline for capstone project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CAPSTONE_SECRET }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ec2-3-94-133-86.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-94-133-86.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/scatdd_capstone
          git pull origin main
          npm run build
          sudo cp -r /home/ubuntu/scatdd_capstone/public/. /var/www/html
        EOF
